---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vzxcvz
resources:
  - ns.yaml
  - vzxcvz-quota.yaml
  - vzxcvz-deploy.yaml
  - vzxcvz-svc.yaml
  - vzxcvz-vs.yaml
  - vzxcvz-hpa.yaml
