---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: vzxcvz-quota
  namespace: vzxcvz
  labels:
    kubernetes.io/metadata.name: vzxcvz
    backstage.io/kubernetes-id: vzxcvz
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
