---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: tets-quota
  namespace: tets
  labels:
    kubernetes.io/metadata.name: tets
    backstage.io/kubernetes-id: tets
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
