apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/instance: certs
  name: diegoluisi.eti.br
spec:
  acme:
    email: contato@diegoluisi.eti.br
    privateKeySecretRef:
      name: issuer-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: us-east-1
      selector:
        dnsZones:
        - diegoluisi.eti.br
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    app.kubernetes.io/instance: certs
  name: ses.io
spec:
  acme:
    email: contato@ses.com
    privateKeySecretRef:
      name: issuer-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: us-east-1
      selector:
        dnsZones:
        - ses.io

